{% set name = "azure-mgmt-network" %}
{% set version = "22.3.0" %}
{% set sha256 = "1993a11b4bdb417deb20956f2e5e0421c435961756ef37086b74b9f46b705c2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3
    - azure-common >=1.1,<1.2
    - msrest >=0.7.1
    - azure-mgmt-core >=1.3.2,<2.0.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.network
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Network Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - timsnyder
    - Maxyme
    - TomAugspurger
