{% set name = "azure-mgmt-network" %}
{% set version = "12.0.0" %}
{% set sha256 = "74502996a4d6c7b3b72e3f57c2ff297263cc02f18fec33363582346a29390094" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - azure-common >=1.1
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.network
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Network Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - Maxyme
