{% set name = "azure-mgmt-network" %}
{% set version = "28.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure_mgmt_network-{{ version }}.tar.gz
  sha256: 8c84bffb5ec75c6e0244e58ecf07c00d5fc421d616b0cb369c6fe585af33cf87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - isodate >=0.6.1
    - typing_extensions >=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.network
    - azure.mgmt.network.aio
  commands:
    - pip check
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Network Management Client Library for Python

extra:
  recipe-maintainers:
    - timsnyder
    - Maxyme
    - TomAugspurger
